### ISSUE TITLE
Content structuring behaviour

### ISSUE THREAD

**Issue by Q-intessence** [SPANDigital/presidium#153]
**Description:**
Environment : develop
Version : v0.2.1
Test case ID(s) : Navigation main menu test folder items
Test execution type(s) : Automation and Exploratory

**Observation(s):**
During exploratory testing the following concerns were picked up on the menu navigation and article structuring: 
1. Empty folders :
    - 4 levels deep or not 
    - Loads incorrect name 
    - On localhost go into directory browsing
    - Builds incorrect path in URL to article (Screenshot : Test Folder 3)
2. Expanding folder : 
    - When over 4 levels deep 
    - Clicking expand folder menu item will add it to the menu as a separate item below the main folder (Screenshot : Test Folder 3)
3. Enabled nested articles:
    - When enabling nesting articles in the main folder are placed last and not first, ahead of the sub folders and sub articles (Screenshot : Test Folder - Nested)
    - When disabling nesting 
        - Only the article is displayed, expected behaviour (Screenshot : Test Folder - Un-nested)
4. Main folder:
    - Only the first article under the main folder others are ignored however subfolders do not behave as such (Screenshot : Test Folder - Un-nested vs folder-content)

**Recommendation(s):**
1. Discussion points on empty directories:
    - Ignore empty folders
    - Default 404 on empty folders (Presidium 404 vs hosted server 404)
    - Correct URL pathing if directory browsing is allowed
2. Discussion points on Folder depth level allowed:
    - Allow user to configure depth level
    - Set a hard limit of 4 levels and anything deeper will be ignored
3. Discussion points on nesting:
    - From the un-nested behaviour a user would expect it first
    - If this is expected behaviour we need document it under nesting section so user can realign their documentation layout 
4. Discussion points on main folder
    - If this is expected behaviour we need document it under nesting section so user can realign their documentation layout 

**Attachements:**
[template-reference.zip](https://github.com/SPANDigital/presidium/files/1847763/template-reference.zip)
[Screenshots.zip](https://github.com/SPANDigital/presidium/files/1847826/Screenshots.zip)

**Comment by ruaanvds** [comment]
Archiving this task, as it will be addressed as part of https://github.com/SPANDigital/presidium/issues/185.
