### ISSUE TITLE
Use nodegit for managing repos in stead of shelljs.

### ISSUE THREAD

**Issue by MaddyCrews** [SPANDigital/presidium#32]

**Comment by MaddyCrews** [comment]
nodegit is very powerful but not immediately clear or easy to use. https://github.com/nodegit/nodegit
The reason why we'd prefer to use nodegit than execute git commands via shelljs is so that presidium is platform agnostic.

**Comment by ruaanvds** [comment]
There's no clear benefit at the moment to introduce nodegit. ShellJS has enough flexibility to cover all current use cases. Closing for now.
