### ISSUE TITLE
Simplify the "getting started" process  

### ISSUE THREAD

**Issue by VirtualTraveler** [SPANDigital/presidium#49]
Review the getting started instructions and try to simplify them even more.

**Comment by dominicfollett** [comment]
The changes I have made here was to break out each item as a call to action and present them in a bite-sized easy follow manner. Additionally, the flow is reflected now in the menu. In this way the way forward appears simpler and deterministic.

**Comment by VirtualTraveler** [comment]
Much better. I think this is now resolved.
