### ISSUE TITLE
Key concepts needs a re-write 

### ISSUE THREAD

**Issue by VirtualTraveler** [SPANDigital/presidium#53]
The key concepts section doesn't really explain Presidium's key concepts. 

Concepts we could explain. Let's build a better list...

1. It's a static website generator with fancy Javascript for navigation and bells a whistles. but its good enough for most uses. We keep it static to make it easy to publish using github as a platform. you don't need to ask permission or get a server setup. you can do it now, today. 
2. The menu structure and associated directory structure are the same. for simplicity and transparency. Content reuse across a site is overrated. focus on creating a meaningful simple  default navigation structure where articles have one and only one home.
3. Micro-articles are good for ownership, focus, and ability to get something done quickly.
4. The authoring workflow. Editing and reviewing content on a local machine then using gitflow or similar to review and publish 
5. Markdown, it's good enough and if you need more use html. 
6. Importing content that is maintained elsewhere saves a lot of work.
7. Its more than a framework. Its a framework built around a process. Yes it's opinionated, but its good enough, and who wants to spend time documenting code? Software documentation that doesn't suck is not just a tagline.

**Comment by ruaanvds** [comment]
@RosyFischer This might be something that you've already done, but I'm assigning this to you. Please see @VirtualTraveler's comments above.

**Comment by VirtualTraveler** [comment]
Rosy

Let's talk about this one, no rush. I think we need to decide what we want to say here. It will probably take some discussion and you will need to take a look at our product strategy document as well

John R. Harris

**Comment by RosyFischer** [comment]
John,
I think this can be closed. You reviewed and approved the new content.
Rosy
