### ISSUE TITLE
How to create sub sections? (please add recipe)

### ISSUE THREAD

**Issue by TheNightbear** [SPANDigital/presidium#70]
As shown in your own [documentation](http://presidium.spandigital.net/recipes/content-structure/) it is possible to build a structure with sub sections:

![grafik](https://user-images.githubusercontent.com/8239167/32923554-77552a9e-cb38-11e7-98d5-5bf0f782c0a2.png)

But how? Can't figure it out. 
Please add a recipe to your documentation, that shows how it's done!

Thx

**Comment by ruaanvds** [comment]
Hi @TheNightbear - thanks for your input! 

We’re going to extend the article [here](http://presidium.spandigital.net/recipes/content-structure/) with a concrete example, but in the meantime, here’s one: 

In this example, I’m adding a sub-section called “my-subsection”, with two child articles: 

```
content 
    ├──_best-practices
            ├──my-subsection
                    ├──test.md
                    ├──test2.md
```

This generates the following: 

![menu-example](https://user-images.githubusercontent.com/6225983/32935281-17d8e8ae-cb78-11e7-9dd4-aec09a955611.png)

The menu's name defaults to the directory name, but if you create an `index.md` in the root of a sub-directory and specify `title` in it's [front matter](https://jekyllrb.com/docs/frontmatter/), you can configure the menu's title. 

Example: 

```
content 
    ├──_best-practices
            ├──my-subsection
                    ├──index.md
                    ├──test.md
                    ├──test2.md
```

The `index.md` file: 

```
---
title: My Sub Menu
---
```

Which generates: 

![menu-example-2](https://user-images.githubusercontent.com/6225983/32935415-c2589b62-cb78-11e7-94e3-5f2f0f756dbd.png)

*Please note, when adding new files, it can often take a few seconds for the local server to reflect file changes.*

**Comment by TheNightbear** [comment]
Thank you @ruaanvds for your quick reply!

With your example I've managend to create such structure. 
But it took me longer then expected :o)

What I have learned:
- **a clear error logging is missing** 
  sometimes I was not aware of a misconfiguration or typo (eg. `titel` instead of `title`)
- **dist folder handling might need attention** 
  more then once I had to stop the app and delete the `dist` folder to produce changes
- **auto regeneration needs attention**
  - changes in the `_config.yml` should take effect without the need to restart the app
  - a finished regeneration should trigger a reload of the browser

**Comment by ruaanvds** [comment]
No problem, @TheNightbear. Thanks for the great feedback. I'm going to close this issue for now, but I've converted your feedback into two separate issues: 

- https://github.com/SPANDigital/presidium/issues/72
- https://github.com/SPANDigital/presidium/issues/73

Thanks again!
