### ISSUE TITLE
Is development continuing?

### ISSUE THREAD

**Issue by palitu** [SPANDigital/presidium#75]
I am looking at using this for a website, but noticed that there has not been any development recently.

Is this project still being developed?

thanks

**Comment by VirtualTraveler** [comment]
Hi Palitu, 

Development is very much continuing. We are currently deploying this solution for server al clients and are hard at work on that. Expect new features and changes as a result of those deployments soon.

**Comment by palitu** [comment]
cool - glad to hear it.  I looked at the history of the project and saw a s significant drop off in activity around june, so i didnt want to commit to a non-developing project.

I am primarily looking for a side menu system, which has decent and modern looking theming, with out being overly complex - and this seems to fit the bill!

**Comment by ruaanvds** [comment]
Hey @palitu - thanks for getting contact. Just to extend @VirtualTraveler's feedback: most of the development is happening in [Presidium Core](https://github.com/SPANDigital/presidium-core), which is the engine that drives Presidium. There are also numerous changes in [Presidium JS ](https://github.com/SPANDigital/presidium-js)(which handles the side navigation), if you're curious.  

We'll likely roll out the latest version (0.1.17) next week, so we'll keep you posted.  👍

**Comment by palitu** [comment]
ah, yes.

Silly me.  Glad to hear :)
